# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import abacus_pb2 as abacus__pb2


class AbacusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendQuery = channel.unary_unary(
                '/Abacus/SendQuery',
                request_serializer=abacus__pb2.Request.SerializeToString,
                response_deserializer=abacus__pb2.Response.FromString,
                )
        self.FreeNode = channel.unary_unary(
                '/Abacus/FreeNode',
                request_serializer=abacus__pb2.Request.SerializeToString,
                response_deserializer=abacus__pb2.Response.FromString,
                )


class AbacusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreeNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AbacusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SendQuery,
                    request_deserializer=abacus__pb2.Request.FromString,
                    response_serializer=abacus__pb2.Response.SerializeToString,
            ),
            'FreeNode': grpc.unary_unary_rpc_method_handler(
                    servicer.FreeNode,
                    request_deserializer=abacus__pb2.Request.FromString,
                    response_serializer=abacus__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Abacus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Abacus(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Abacus/SendQuery',
            abacus__pb2.Request.SerializeToString,
            abacus__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FreeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Abacus/FreeNode',
            abacus__pb2.Request.SerializeToString,
            abacus__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
